import type { Metadata } from 'next';
import { Geist_Mono } from 'next/font/google';

import Providers from '@/components/providers/query-client-provider';

import './globals.css';

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistMono.variable}`}>
      <body className="font-sans antialiased">
        <nav className="border-b border-zinc-200 px-4 py-3 dark:border-zinc-800">
          <div className="mx-auto flex max-w-3xl items-center gap-6">
            <a
              href="/"
              className="font-medium text-zinc-900 hover:text-zinc-700 dark:text-zinc-100 dark:hover:text-zinc-300"
            >
              Home
            </a>
            <a
              href="/docs/swagger"
              className="font-medium text-zinc-900 hover:text-zinc-700 dark:text-zinc-100 dark:hover:text-zinc-300"
            >
              API 문서 (Swagger)
            </a>
          </div>
        </nav>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
